server:
  port: 5430
  servlet:
    context-path: /invoiceControl
  tomcat:
    min-spare-threads: 10
    max-threads: 20
    uri-encoding: utf-8

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:testdb;IFEXISTS=FALSE;
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

amount_limit: 600



